### ISSUE TITLE
Game does not end

### ISSUE THREAD

**Issue by unseenmagik** [bobloy/Fox-Cogs#5]
Hay Blobby. 

Loaded this cog to my bot from your repo. 
Great cog but I found one issue. 
The game does not auto stop or cancel when a word is found. 

I cmd [p]hangman and it says a game is already running. A command is needed to stop a current game. 

Also is this cog global to the bot or specific to a player who initiates the command ? 

I’ll take a look at the code if you want me too. 

Regards
Magik

**Comment by bobloy** [comment]
Game currently runs global, and answers can be submitted by any player. 
I can add a stophang command to cover for situations like this. 
A system to timeout games would probably cover this error as well.

**Comment by unseenmagik** [comment]
If your able to add that into the cog Simply enough that would be ideal :-)

**Comment by bobloy** [comment]
60a5ec31880d4880396987f444b8325761e1d9b2
